### ISSUE TITLE
Have <Dialog /> support disableFocusLock property

### ISSUE THREAD

**Issue by MartinezEst** [coingaming/moon-design#2562]
## Is Your Feature Request Related to a Problem?

I currently have this ticket -> https://coingaming.atlassian.net/browse/SBFE-1104

It involves having a modal open and then opening cashier -> clicking on an input inside cashier. Since reach-portal modals have a focus lock component then I would want to disable the focus lock in this case where cashier is open. 

## Describe the Solution You'd Like

I would like to add a new property to <Dialog /> -> `disableFocusLock` which will toggle `dangerouslyBypassFocusLock` boolean internally in the reach-portal component.

## Describe Alternatives You've Considered

There really isn't a simpler way imo.

**Comment by dkireev** [comment]
Would `disableFocusLock` be a boolean with `false` by default?
